version: 2
updates:
  - package-ecosystem: "pip"
    directory: "requirements/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "pip dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "npm dependencies"
      