blank_issues_enabled: false

contact_links:
  - name: Common Issues
    url: https://en.readthedocs.io/en/latest/faq.html
    about: Check if your issue already has solutions
  - name: Edgelab Documentation
    url: https://faq.readthedocs.io/en/latest/
    about: Check if your question is answered in docs