name: smoke-test

on:
  push:
    branches:
      - dev # should be 'main' later
    paths:
      - 'requirements/**'
      - 'scripts/**'
      - 'environment.yml'
      - 'environment_cuda.yml'
      - 'requirements.txt'
      - 'requirements_cuda.txt'
      - 'setup.py'
      - '.github/workflows/smoke-test.yml'

  schedule:
    - cron: '0 0 * * *'

jobs:
  manual-installation:
    name: manual installation test for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          ref: dev # should be main later

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: pip install deps
        run: |
            python -m pip install --upgrade pip wheel setuptools
            python -m pip install -r requirements/pytorch_cpu.txt
            python -m pip install -r requirements/base.txt
            python -m pip install -r requirements/inference.txt
            python -m pip install -r requirements/export.txt
            python -m mim install -r requirements/mmlab.txt
            python -m mim install -e .
            python --version
            python -m pip --version
            python -m pip list

  auto-installation:
    name: auto installation test for (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          ref: dev # should be main later

      - name: setup deps
        run: |
            bash scripts/setup_linux.sh
